# Generated by Django 3.0.10 on 2021-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('province_id', models.IntegerField()),
                ('province', models.CharField(max_length=200)),
                ('tipe', models.CharField(max_length=100)),
                ('city_name', models.CharField(max_length=100)),
                ('postal_code', models.IntegerField()),
            ],
        ),
    ]
