# Generated by Django 3.0.10 on 2021-02-13 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='tipe',
            new_name='type',
        ),
    ]
